### ISSUE TITLE
Extend `aut validator info` to also work with eNode

### ISSUE THREAD

**Issue by h-faust** [autonity/autcli#95]
Currently there seems to be no quick/easy way to find a validator ID/address; `aut validator info` only works with providing the ID in the first place; it would be useful if it could also just work with an eNode (and in fact could automatically distinguish whether what it's been given for the `--validator` argument is an ID/address, or an enode, based on their length.

**Comment by dtebbs** [comment]
The latest version of the tool includes the `validator compute-address` command which I think can be used for this.

**Comment by dtebbs** [comment]
I'm keen to avoid too much abstraction in the tool and provide queries that are close to the real chain / contract queries. 

Closing for now. Please reopen if you think something is missing.
