### ISSUE TITLE
New account created cause `ValueError: non-hexadecimal number found in fromhex() arg at position 0` when imported by `import-private-key`

### ISSUE THREAD

**Issue by chrisckwong821** [autonity/autcli#98]
To reproduce;
```aut account new```
Then:
```aut account import-private-key ./.autonity/keystore/XXX.key```
-> ```ValueError: non-hexadecimal number found in fromhex() arg at position 0```
---
aut, version 0.1.2
Mac OS Monterey

**Comment by dtebbs** [comment]
Thanks @chrisckwong821 .  I think you are attempting to import an encrypted key, rather than a raw private key.
The keystore files used by autonity can be used as-is, so there is no need to import.  You should be able to just refer to the files and use them.

**Comment by dtebbs** [comment]
I'll close for now, but feel free to reopen if you hit more problems.

**Comment by dtebbs** [comment]
(BTW, feel free to propose a change to the docs if anything is unclear).
